user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /

wechat_api:
    resource: "@WechatApiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
