services:
#    article.example:
#        class: ArticleBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
        form.articleadd:
          class: ArticleBundle\Forms\articleadd
          scope: request
          arguments: [@request, @service_container]

        form.articleedit:
          class: ArticleBundle\Forms\articleedit
          scope: request
          arguments: [@request, @service_container]

        form.articledel:
          class: ArticleBundle\Forms\articledel
          scope: request
          arguments: [@request, @service_container]

        form.articlelist:
          class: ArticleBundle\Forms\articlelist
          scope: request
          arguments: [@request, @service_container]

        form.articleinfo:
          class: ArticleBundle\Forms\articleinfo
          scope: request
          arguments: [@request, @service_container]
