services:
        user.listener.controller:
            class: UserBundle\EventListener\listenerController
            arguments: [@router, @service_container]
            tags:
                - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

        user.listener.request:
            class: UserBundle\EventListener\listenerRequest
            scope: request
            arguments: [@request, @service_container]
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
